import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './Navbar/page'
import cover from '../../public/cover.jpg'
import Image from 'next/image'
import Footer from './Footer/page'

import Home from './page'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My First Next.js Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavBar/>  
      <Image src={cover} alt="cover" className=""/>
      {/* <Home/> */}
      
      

      
        {children}
        
        <Footer/>
        {/* <Contact/> */}
        </body>
    </html>
  )
}
